group:
  helper:
    command_use_on: #Команды которые выполняються при начале работы
      - "tab player %player% tabprefix &6&lHELPER &f"
      - "lp user %player% permission set litebans.mute true"
    command_use_off: #Команды которые выполняються при окончании работы
      - "tab player %player% tabprefix &7&lHELPER &f"
      - "lp user %player% permission set litebans.mute false"
    premission: "ghoststaff.use.helper" #Права, чтобы плагин знал какие команды выполнять
  sthelper:
    command_use_on:
      - "tab player %player% tabprefix &6&lST.HELPER &f"
      - "lp user %player% permission set litebans.mute true"
    command_use_off:
      - "tab player %player% tabprefix &7&lST.HELPER &f"
      - "lp user %player% permission set litebans.mute false"
    premission: "ghoststaff.use.sthelper"
  moder:
    command_use_on:
      - "tab player %player% tabprefix &9&lMODER &f"
      - "lp user %player% permission set litebans.ban true"
    command_use_off:
      - "tab player %player% tabprefix &7&lMODER &f"
      - "lp user %player% permission set litebans.ban false"
    premission: "ghoststaff.use.moder"

messages:
  prefix: "&x&0&8&4&C&F&B&lG&x&1&A&5&F&F&B&lh&x&2&D&7&1&F&B&lo&x&3&F&8&4&F&C&ls&x&5&1&9&6&F&C&lt&x&6&4&A&9&F&C&lS&x&7&6&B&B&F&C&lt&x&8&8&C&E&F&D&la&x&9&B&E&0&F&D&lf&x&A&D&F&3&F&D&lf &8»" #Префикс
  message_on: #Сообщение при начале работы
    - "&7"
    - "%prefix% &fВы &aуспешно &fначали работу на &6сервере&f!"
    - "&7"
  message_off: #Сообщение при окончании работы
    - "&7"
    - "%prefix% &fВы &aуспешно &cзакончили &fработу на &6сервере&f!"
    - "&7"
  hasnt_permission: #Сообщение если нет прав
    - "&7"
    - "%prefix% &fВы &cне имеете &fправа &aиспользовать &fданную команду!"
    - "&7"