name: GhostStaff
version: '1.0'
main: me.ghostpanters.ghoststaff.GhostStaff
api-version: '1.16'
author: GhostPanters
website: https://GhostStudio.online

commands:
  sw:
    description: "Команда для активації/деактивації режиму роботи."
    usage: "/sw <on|off>"
    permission: "ghoststaff.use"
  ghoststaff:
    description: "Команды управления плагином GhostStaff."
    usage: "/ghoststaff reload"
    permission: "ghoststaff.reload"
permissions:
  ghoststaff.use:
    description: "Разрешение на использование команд /sw."
    default: true
  ghoststaff.reload:
    description: "Разрешение на перезагрузку конфигурации плагина."
    default: op